### ISSUE TITLE
Craft {% switch %} statements will not be formatted correctly

### ISSUE THREAD

**Issue by qinyiyao** [mblode/vscode-twig-language-2#10]
PrettyDiff currently does not work properly when a Craft `switch` statement is used. 

Inserted code snippet, properly indented:
```
{% switch variable %}
  {% case "value1" %}
  {% case "value2" %}
  {% default %}
{% endswitch %}

{% some other statement %}
```

Saved file, unclosed indentation:
```
{% switch variable %}
{% case "value1" %}
  {% case "value2" %}
    {% default %}
    {% endswitch %}

    {% some other statement %}
```

Although `switch` is not really a standard but it would be great to support it as Craft uses it extensively.

**Comment by mblode** [comment]
0.12.0 handles Craft switch blocks and includes a regression test.
