### ISSUE TITLE
ELSEIF Autocomplete not working

### ISSUE THREAD

**Issue by thomasfrobieter** [mblode/vscode-twig-language-2#101]
While IF, ELSE & ENDIF works well, ELSEIF doesn't work in v0.9.2

**Comment by thomasfrobieter** [comment]
Ah sorry, didn't saw the existing issue: https://github.com/mblode/vscode-twig-language-2/issues/83 **closed**

**Comment by mblode** [comment]
The elseif and apply/endapply snippets are included in 0.12.0.
