### ISSUE TITLE
Wrong setting

### ISSUE THREAD

**Issue by T1ckbase** [mblode/vscode-twig-language-2#104]
![image](https://github.com/mblode/vscode-twig-language-2/assets/146760065/a88c7d6c-80ba-48e4-97d5-ae66f5d64b4a)

I think this is the correct setting
```
"files.associations": {
    "*.twig": "html"
},
"emmet.includeLanguages": {
    "twig": "html"
},
```

**Comment by mblode** [comment]
The settings descriptions are corrected in 0.12.0. Thanks for flagging this.
