### ISSUE TITLE
Incompatibility with Baptiste Darthenay's Django extension

### ISSUE THREAD

**Issue by Alban2701** [mblode/vscode-twig-language-2#112]
Well, I succed to correct my problem but I want to write it here in the case of someone get the same problem.

I had the Django's extension of Baptiste Darthenay on my VS CODE and when I wanted to use Twig Language (1 or 2), the highlights weren't there. 

Think to deactivate Django's extension and, for my part, it worked.

Have a nice day !

**Comment by mblode** [comment]
0.12.0 includes activation fixes, but I haven’t verified this extension combination. Please try selecting Twig Language 2 as the default formatter.
