### ISSUE TITLE
{% do %} Tag always with newline

### ISSUE THREAD

**Issue by PapsOu** [mblode/vscode-twig-language-2#14]
Hello,

First, thank you for your very good extension.

When formatting a twig template with a [do](https://twig.symfony.com/doc/2.x/tags/do.html) tag, a new line is always append afer the `do` keyword.

Is it possible to keep on one line do statements ?

Example :

```twig
{% do form.myField.setRenderer() %}
```

Is formatted as :

```twig
{% do 
form.myField.setRenderer() %}
```

Should be formatted as 

```twig
{% do form.myField.setRenderer() %}
```

Thank you

**Comment by mblode** [comment]
0.12.0 preserves do expressions and includes a regression test for this case.
