### ISSUE TITLE
'Format Document' command doesn't work

### ISSUE THREAD

**Issue by chasegiunta** [mblode/vscode-twig-language-2#15]
While I can paste in code, and the formatter is ran, I cannot trigger it manually through the 'Format Document' command via CMD+Shift+P. Any ideas?

**Comment by mblode** [comment]
Hey @chasegiunta,

**Comment by chasegiunta** [comment]
@mblode looks like this is still around. I was hopeful that it was just a conflicting keyboard command, but this still occurs (or doesn't occur, actually) if you run the command manually from the command palette (command-shift-p , format document)

**Comment by chasegiunta** [comment]
Just to reiterate, I can still select all and run 'Format Selection' to format the entire document just fine, just not the 'Format Document' command.

**Comment by mblode** [comment]
Are you able to look at the dev console in VS Code?
I believe it is: Help --> toggle developer tools --> console

Then just send me any necessary logs of when you try the format document command and hopefully we can fix the bug.

Thank you!

**Comment by chasegiunta** [comment]
Ah! This ended up being a conflict with Prettier. I didn't realize Prettier was also trying to format my code. *sinks into chair*

**Comment by mblode** [comment]
0.12.0 includes packaged-extension activation and formatting tests. Please share the Output error if formatting still won’t start.
