### ISSUE TITLE
Unexpected token after formatting using in array

### ISSUE THREAD

**Issue by rroblik** [mblode/vscode-twig-language-2#17]
Hi,

When I format my Drupal Twig template using this extension (<kbd>Maj</kbd> + <kbd>Alt</kbd> + <kbd>F</kbd>), the following code
```twig
{% if service_status in ['deprecated', 'wip'] %}
    {{ content.field_service_status }}
{% endif %}
```

is badly formatted to
```twig
{% if service_status in['deprecated', 'wip'] %}
    {{ content.field_service_status }}
{% endif %}
```

Without space between `in` and `[` ; that throw a `Twig_Error_Syntax` fatal error.

The space (only one) SHOULD remain here :)

Best regards

**Comment by mblode** [comment]
0.12.0 preserves these Twig expressions and includes regression tests for the reported formatting cases.
