### ISSUE TITLE
Format document adds spaces around pipes (Twig filters)

### ISSUE THREAD

**Issue by thomasfrobieter** [mblode/vscode-twig-language-2#18]
`{% if content.left|render|striptags|trim|length > 0 %}
    bla
{% endif %}`

is formatted to:

`{% if content.left | render | striptags | trim | length > 0 %}
    bla
{% endif %}`

**Comment by mblode** [comment]
0.12.0 preserves Twig filter expressions without rewriting the pipe spacing. Added regression coverage for these cases.
