### ISSUE TITLE
Difference from vscode-twig-language

### ISSUE THREAD

**Issue by alexchantastic** [mblode/vscode-twig-language-2#2]
It might be worthwhile to add what is different about this extension vs [vscode-twig-language ](https://github.com/mblode/vscode-twig-language).

**Comment by montchr** [comment]
If this fixes issues with the other plugin, why is there a need for this new plugin? I'm just trying to figure out which one to install but it looks like both plugins are still being updated.

**Comment by lems3** [comment]
> If this fixes issues with the other plugin, why is there a need for this new plugin? I'm just trying to figure out which one to install but it looks like both plugins are still being updated.

We also would like to understand the difference between the two extensions...

**Comment by Flowgram** [comment]
> > If this fixes issues with the other plugin, why is there a need for this new plugin? I'm just trying to figure out which one to install but it looks like both plugins are still being updated.
> 
> We also would like to understand the difference between the two extensions...

The difference is detailed here: https://github.com/mblode/vscode-twig-language-2#what-has-changed-since-version-1

It does appear that both extensions are abandoned though.

**Comment by mblode** [comment]
Both extensions now share the same formatter and grammar. Twig Language keeps HTML mode; Twig Language 2 keeps its separate Twig mode.
