### ISSUE TITLE
Formatter collapses multi-line include CSS and JS blocks into single line

### ISSUE THREAD

**Issue by ciw1973** [mblode/vscode-twig-language-2#20]
Multi-line blocks of CSS (includecss / endincludecss) and Javascript (includejs / endincludejs) code are collapsed down to a single line by the formatter.

I don't imagine anyone would want this behaviour.

Ideally, the contents would be formatted using the appropriate language formatter, or at least indented based on the current tab settings, but an option so these blocks aren't always collapsed into one line would at make the extension usable for templates which include them.

**Comment by mblode** [comment]
0.12.0 preserves custom CSS/JS block contents, including their line breaks.
