### ISSUE TITLE
Formatter removes space after "and" in some cases

### ISSUE THREAD

**Issue by renestalder** [mblode/vscode-twig-language-2#21]
I had this code snipped recently:

```twig
{% if sections | default and sections | length > 0 and (sections | first).title | default %}
    <hr>
{% endif %}
```

Which gets formatted to...

```twig
{% if sections | default and sections | length > 0 and(sections | first).title | default %}
    <hr>
{% endif %}
```

... by removing the space after the `and` when the next section is wrapped in round brackets.

**Comment by renestalder** [comment]
Probably the same as #17?

**Comment by mblode** [comment]
0.12.0 preserves these Twig expressions and includes regression tests for the reported formatting cases.
