### ISSUE TITLE
Setting files.associations breaks file icons for HTML files

### ISSUE THREAD

**Issue by grantiverson** [mblode/vscode-twig-language-2#22]
When I include `"files.associations": { "*.html": "twig" }` in the settings for VS Code, all of my HTML files' icons are changed to those of "unknown" filetypes.

![screen shot 2018-09-19 at 11 51 22 am](https://user-images.githubusercontent.com/13042286/45765261-9fb20280-bc02-11e8-95c7-42c1c038dde9.png)

![screen shot 2018-09-19 at 11 50 50 am](https://user-images.githubusercontent.com/13042286/45765248-99238b00-bc02-11e8-882a-737b4e282740.png)

**Comment by mblode** [comment]
Oh sorry about that! One workaround is installing the Material Icon Theme extension: https://marketplace.visualstudio.com/items?itemName=PKief.material-icon-theme

**Comment by grantiverson** [comment]
Well, that works, but I'm not sure if I like the icon theme. I'll have to play around with it. Thanks!

**Comment by mblode** [comment]
File icons still depend on your icon theme and language association. Please share your settings if this persists on 0.12.0.
