### ISSUE TITLE
Option to disable formatter

### ISSUE THREAD

**Issue by muuvmuuv** [mblode/vscode-twig-language-2#24]
I'm using [Unibeautify](https://unibeautify.com/) to format my code. Please add an option to disable your formatter integration. 😁

**Comment by mblode** [comment]
Hey @muuvmuuv, I've added the ability to turn off the Twig Language formatting in settings. If you search it in the VSCode settings, you can find it under "Twig-Language-2: Formatting" and just uncheck the checkbox. Thanks 😄

**Comment by mblode** [comment]
You can disable formatting with "twig-language-2.formatting": false. 0.12.0 applies that setting without a restart.
