### ISSUE TITLE
{% set %} with inline if statement broken after formatting - at least sometimes

### ISSUE THREAD

**Issue by thomasfrobieter** [mblode/vscode-twig-language-2#25]
I don't even understand whats going on here, but:

This is formatted correctly:
```
{% set full_size_overlay = rendercontent['field_overlay_sizing'][0]['#markup'] == 'full-size' ? true : false %}
```
(no changes after formatting)

While this (one line after the example above):
```
{% set show_overlay = rendercontent.field_overlay_position[0]['#markup'] == 'disabled' ? false : true %}
```
becomes:
```
{% set show_overlay = rendercontent.field_overlay_position[0]['#markup'] == 'disabled'
  ? false
  : true %}
```

If i change the 'disabled' to 'dis-abled' it works.

**Comment by thomasfrobieter** [comment]
f i add a hyphen in the 'disabled' >> 'dis-abled' it works ..

**Comment by mblode** [comment]
0.12.0 preserves these Twig expressions and includes regression tests for the reported formatting cases.
