### ISSUE TITLE
Disable attributes chaining

### ISSUE THREAD

**Issue by ptrwllrd** [mblode/vscode-twig-language-2#27]
Let's say I have a widget in my template formatted like this:

```
<widget
  template="flexbox"
  class="active-tickets"
  status="active"
  component-template="active"
  time-frame="0"
></widget>
```

The attributes are broken down into their own lines for readability and clearer diffs. Is there a way to disable inlining/chaining back to a single line them upon formatting?

**Comment by mblode** [comment]
Hey @ptrwllrd, I have just pushed an update to Twig Language 2 with a brand new formatter using Prettydiff 3 which brings about some major bug fixes. This bug has now been fixed in the newest version of the extension, you will just need to change the settings "Twig-Language-2: Wrap" to `80`.

**Comment by mblode** [comment]
0.12.0 supports attribute wrapping through the existing forceAttribute and wrap settings.
