### ISSUE TITLE
Line spaces taken out

### ISSUE THREAD

**Issue by Flowgram** [mblode/vscode-twig-language-2#28]
Hi there, 

Thanks so much for your continued work on this, it's really great that some of the long-term bugs have been fixed.

Prettydiff 3 appears to be removing blank line breaks where previously they were left alone. I sometimes leave line spacing in my html/twig for readability purposes. 

I'm wondering if there's a way of ignoring these, like before.

Many thanks

**Comment by renestalder** [comment]
I have the same issue. It's quite a major issue. All my code is completely collabsed to one big block of code. Every empty line break, doesn't matter if between variables, macros or code comments, is removed. @mblode I hope you can tackle this as soon as possible.

**Comment by mblode** [comment]
Ok, I've fixed this now, and there is an option to set the number of new lines you would like to preserve under "twig-language-2.preserve". By default this is set to 1

**Comment by mblode** [comment]
0.12.0 preserves existing line breaks in these template layouts. Added regression coverage.
