### ISSUE TITLE
Just so broken...

### ISSUE THREAD

**Issue by crazedVic** [mblode/vscode-twig-language-2#29]
Had to revert to previous version. was removing entire sections of code on format document.  also the indentation is crazy wide now, makes it impossible to use.

I can email you sample twig files if you want to replicate both issues, don't really want to post them here.

**Comment by mblode** [comment]
@crazedVic Thank you for posting to a Github issue and for leaving a VS Code extension review. Please email me at m.blode@gmail.com and send any information about these issues that you have.

I'm really sorry you are having all of those issues! I'm wondering whether it has anything to with the VS Code settings for Twig Language 2, where some have changed. I believe that setting Twig Language 2 Tab Size to 0 in settings may correct for the crazy indentation. But the deleting portions of code is not acceptable and brand new to me and I will need to fix that ASAP.

Sorry again,
Matt

**Comment by ssnukala** [comment]
I am also having issues with this extension, with every save it removes large chunks of code. And in about 3 saves the whole file is empty. Had to disable this extension to stop this behavior

**Comment by clarknelson** [comment]
I'm also experiencing this issue :(

**Comment by clarknelson** [comment]
I believe it has to do with inline `<script>` tags. The first time you save, all of the code except for the javascript is removed. Saving again will remove the javascript code. Files without any `<script>` tags are just emptied.

**Comment by proutek** [comment]
I'm having same issue. Had to downgrade to 0.3.1. This issue occurs since 0.4.0.

**Comment by clarknelson** [comment]
i've just removed the plugin and fallen back to vs code's HTML formatting/highlighting. would love to add this back one day when the formatting issue is fixed!

**Comment by tomodwyer** [comment]
> I'm having same issue. Had to downgrade to 0.3.1. This issue occurs since 0.4.0.

Same for me. v0.3.1 appears to be the last working version that behaves as expected.

**Comment by mblode** [comment]
I'm still very sorry about this disastrous bug with Twig Language extension using PrettyDiff 3 and I've attempted many times to get to the bottom of the issue but to sadly, no avail. I definitely recommend downgrading to version 0.3.1 of this extension to solve this issue as it was the last version to use the older PrettyDiff 2. I will keep searching for a solution and you will be the first to know once the problem has been solved! Thank you for your patience

**Comment by maxfenton** [comment]
Can you put 0.3.1 back into the Marketplace or push a new version that reverts to 0.3.1 but calls it a later version?

**Comment by mblode** [comment]
Hey everyone, I've fixed the issue! 🍾😄 I've re-written how the extension parses the document to ignore script tags. This has officially fixed the problem and the formatter no longer deletes the entire document (thank god). You'll just need to update to version 0.7.1 of Twig Language 2 👍 

Please let me know if you are still having any issues.

**Comment by spoeken** [comment]
Comments get more and more indentation for each time I save :/ 

```{#
                    hello
                    #}```

**Comment by mblode** [comment]
0.12.0 preserves Twig-generated script content and supports ignored regions. Please share any remaining failure as a small example.
