### ISSUE TITLE
Wrong filter formatting

### ISSUE THREAD

**Issue by jezikk** [mblode/vscode-twig-language-2#3]
Filters are wrongly formatted as they are inconsistent with Twigcs Linter:

![filter](https://user-images.githubusercontent.com/7671531/36060120-c9ae9706-0e42-11e8-86b0-d600f59284f2.PNG)

Filters are formatted like this:
```
 {% if (order.getOrderItems | default('') | length > 0) and (productBonusPrice | default('') | length > 0) %}
```
But should be formatted like this without whitespaces around:
```
 {% if (order.getOrderItems|default('')|length > 0) and (productBonusPrice|default('')|length > 0) %}
```

Please, is it possible to fix it?

**Comment by mblode** [comment]
@jezikk Yeah this is a really annoying limitation with PrettyDiff, the Twig formatter I am using. Technically you are developing the way they specify in the Twig docs but PrettyDiff reformats it with spaces. I can raise the issue with the developer of PrettyDiff and hopefully they can solve your issue.

**Comment by jezikk** [comment]
Thank you for answer. It would be great to have this update. :) Because this is an issue in the PrettyDiff dependency, feel free to close the issue if you want.

**Comment by mblode** [comment]
0.12.0 preserves Twig filter expressions without rewriting the pipe spacing. Added regression coverage for these cases.
