### ISSUE TITLE
Strange format behavior

### ISSUE THREAD

**Issue by blackbart420** [mblode/vscode-twig-language-2#34]
Hello,
thank you very much for this plugin, it is very usefull !

I just have a question, I don't know if it is a bug or if this is the wanted behavior :

```
{% if is_front %}
            <header id="region-header" role="banner" style='background-image:url("{{ file_url(node.field_image_header.entity.fileuri) }}")'>
            {% else %}
                    <header id="region-header" role="banner">
                    {% endif %}
```

In this case, IF ELSE and ENDIF are not indented on the same level, where it would make more sense to me if it was...
Is it supposed to be like that ?

Thank you.

**Comment by mblode** [comment]
Hey @blackbart420, I just looked into this issue further and I believe the formatter wants a closing tag for the header within each block of the if statement which would break your code.

Another way to write it, so it gets formatted properly is:

```html
<header id="region-header" role="banner" {% if is_front %}style='background-image:url("{{ file_url(node.field_image_header.entity.fileuri) }}")'{% endif %}>
```

Sorry this is not ideal but thank you for raising the issue!

**Comment by blackbart420** [comment]
Hi @mblode ! 
Actually, your way of writing it is good enough, thank you :)

**Comment by mblode** [comment]
0.12.0 is out with a new formatter. I couldn’t confirm this exact case; please share a small example if it still happens.
