### ISSUE TITLE
Formatting issues after vscode March 2019 update

### ISSUE THREAD

**Issue by manolis1g** [mblode/vscode-twig-language-2#35]
Hello 

Everything was working just fine since yestreday. Today I updated vscode to the March 2019 release and although twig formatting is done ok all the javascript code is turning into lines like this:

```
[36mLine: 1[0m
[31m<!--[0m
[31m$('.date').datetimepicker({[0m
[31m        language: '{{ datepicker }}',[0m
[31m        pickTime: false[0m
[31m    });[0m****
```

I dont know if this is a vscode issue or it's something your end. 

I tried formatting a .tpl file that has html and javascript and it worked just fine which makes me think that it has to do something with this twig extension and not vscode itself. 

Any help would be appreciated. 

Thank you 
Manolis

**Comment by brennaveen** [comment]
I'm also experiencing this issue.

Before format:
```
<script>{% include "rfc/index.js" %}</script>
```

After Format:
```
    <script>

[36mLine: 1[0m
[31m{% include "rfc/index.js" %}[0m
[32m(empty line)[0m
[32m(empty line)[0m

</script>
```

**Comment by mblode** [comment]
Hey @brennaveen and @manolis1g, thank you for bringing up this issue! I'm facing it too. The fix I pushed for it also meant that sometimes, the formatter wouldn't work at all so I reverted it. However, I think I'll revert it back because this issue is more drastic.

**Comment by manolis1g** [comment]
Hello @mblode 

Thanks for your reply. Should we hope for a final fix at some point?

**Comment by mblode** [comment]
I've pushed a fix for this issue but please let me know if you're still running into any issues 👍

**Comment by manolis1g** [comment]
Thanks. I think this has been fixed now.  
There are some minor formatting issues that dont break the page but dont know if this is the right place to talk about them or create a new topic.

**Comment by mblode** [comment]
Thanks for testing it and letting me know 😄 Please make a new issue, they are usually related to the formatter (PrettyDiff 3) and I'll bring it up with the developer

**Comment by mblode** [comment]
0.12.0 replaces PrettyDiff and adds regression tests for the historical formatting failures. Please share any example that still breaks.
