### ISSUE TITLE
Javascript / CSS language support in {% js/css %} blocks?

### ISSUE THREAD

**Issue by gmhenderson** [mblode/vscode-twig-language-2#36]
Hello and thank you for the extension. Would it be possible to get JS/CSS language support inside `{% js %}` and `{% css %}` tags?

I don't know too much about what is required for this, but I did find a related bundle for Sublime/Textmate (https://github.com/barrelstrength/Craft-Twig.tmbundle/blob/master/Syntaxes/Craft-Twig.tmLanguage). Inside that file I found this block:

```
<dict>
  <key>begin</key>
  <string>(?ix)   # Enable free spacing mode, case insensitive
            # Make sure our opening js tag has word boundaries
            (?&lt;=\{\%\sjs\s\%\}|\{\%\sincludejs\s\%\})
          </string>
  <key>comment</key>
  <string>Add JS support to set tags that use the pattern "css" in their name</string>
  <key>end</key>
  <string>(?ix)(?=\{\%\sendjs\s\%\}|\{\%\sendincludejs\s\%\})</string>
  <key>name</key>
  <string>source.js.embedded.twig</string>
  <key>patterns</key>
  <array>
    <dict>
      <key>include</key>
      <string>source.js</string>
    </dict>
  </array>
</dict>
```

and when I added that block to the `twig.tmLanguage` file in this plugin, I then got support for `{% js %}` blocks. I'm not sure if that helps much or not :)

**Comment by mblode** [comment]
Amazing thank you! I just added this block of code to the `twig.tmLanguage` and it's successfully added syntax highlighting for javascript. I'll push an update shortly 😄

**Comment by gmhenderson** [comment]
Well if that's indeed all there is too it, then there's one additional block needed, for CSS support in `{% css tags %}:

```
<dict>
    <key>begin</key>
    <string>(?ix)   # Enable free spacing mode, case insensitive
                (?&lt;=\{\%\scss\s\%\}|\{\%\sincludecss\s\%\}|\{\%\sincludehirescss\s\%\})
                </string>
    <key>comment</key>
    <string>Add CSS support to set tags that use the pattern "css" in their name</string>
    <key>end</key>
    <string>(?ix)(?=\{\%\sendcss\s\%\}|\{\%\sendincludecss\s\%\}|\{\%\sendincludehirescss\s\%\})</string>
    <key>name</key>
    <string>source.css.embedded.twig</string>
    <key>patterns</key>
    <array>
        <dict>
            <key>include</key>
            <string>source.css</string>
        </dict>
    </array>
</dict>
```

**Comment by mblode** [comment]
The js/css block grammar is retained in 0.12.0, and formatting preserves custom block contents.
