### ISSUE TITLE
Better Intellisense

### ISSUE THREAD

**Issue by Spown** [mblode/vscode-twig-language-2#4]
I moved from [TWIG Pack](/whatwedo/vscode-twig/) to this ext, because the former is basically abandoned and looses functionality with every VSC release. But The first thing I've noticed is the limited Intellisense in this one in comparison:

TWIG Pack
![](https://drive.google.com/uc?id=1_mf8tUL4DKh6S6PTUhm3r5UZBxT7AsXA)
![](https://drive.google.com/uc?id=10F5mogXucLShswxeOW27x_GG1dpz1fqs)

Twig Language 2:
![](https://drive.google.com/uc?id=1xNBWcg2HVjsznjb9mahDSfdnKaEBEuZV)
![](https://drive.google.com/uc?id=1BT71e6f3aibLA0R6xAN3Dlk_6pC0_YDs)

Would be nice if the good parts of TWIG Pack could be salvaged into this extension.

Thank you.

**Comment by mblode** [comment]
@Spown Yeah this is a limitation with how I have implemented Twig Language 2. However, my other Twig Language extension works with HTML5 intellisense and should solve your issue 😄 

Check it out here: https://github.com/mblode/vscode-twig-language

**Comment by Spown** [comment]
@mblode Yeah, I've tried your other Twig Language for couple of days and its not that different from TWIG Pack. In particular the straw that broke the camel's back in TWIG Pack's case was that TWIG Pack's commenting (``{# ... #}``) is now ignored and instead html's ``<!-- ... -->`` is used. This is the case in Twig Language as well. Twig Language 2 doesn't suffer from that uses comment ``{# ... #}``.

**Comment by mblode** [comment]
HTML completion, hover and closing tags are now included in 0.12.0. Thanks for raising this.

**Comment by Spown** [comment]
well, jeez, thank you I guess... but 8 years later I don't even remember what I was using it for...
