### ISSUE TITLE
[Formatting] Stop replace tabs into spaces

### ISSUE THREAD

**Issue by kanlukasz** [mblode/vscode-twig-language-2#40]
Hello

I have a problem/question about `Format Document` option - is it possible to stop replace tabs into spaces? I prefer tabs (not spaces)

**Comment by mjsarfatti** [comment]
If I may add, it should also respect the `.editorconfig`, if existing

**Comment by turnstylerj** [comment]
Any chance of this getting fixed? Unfortunately preventing me from being able to use this extension.

**Comment by oak-wildwood** [comment]
We'd really like this too!

**Comment by mblode** [comment]
This has finally been resolved with the most recent update to the extensions (0.9.0). You can now choose the indentStyle in the config.

Thank you so much for your patience!

**Comment by mblode** [comment]
0.12.0 uses the document’s tab size and indentation style. Added tests for spaces, tabs and settings changes.
