### ISSUE TITLE
Doctype doesn't respect preceding new line if previous line contains {% %}

### ISSUE THREAD

**Issue by brennaveen** [mblode/vscode-twig-language-2#41]
My DOCTYPE tag keeps moving to the previous line on format if the previous line contains {%% }

Before Format
```
{% import "/_macros.twig" as macros %} 
<!DOCTYPE html>
```

After Format
```
{% import "/_macros.twig" as macros %} <!DOCTYPE html>
```

**Comment by mblode** [comment]
This has been fixed in the latest update 👍

**Comment by mblode** [comment]
0.12.0 preserves the boundary before the doctype and includes a regression test.
