### ISSUE TITLE
Anchor tag containing twig href broken in <li> parent

### ISSUE THREAD

**Issue by brennaveen** [mblode/vscode-twig-language-2#42]
When I use anchor tags with a twig variable for the `href` inside of a `li` tag, the formatter is combining the `a` and `href` into a single tag.

Before format
```
<li><a href="{{ path_for('home') }}">Home</a></li>
```
After format
```
<li><ahref="{{path_for('home')}}">Home</a></li>
```

**Comment by brennaveen** [comment]
I just noticed it's not just the `href` attribute affected and discovered an add workaround.

Before format:
```
<a {{'href="' ~ path_for('home') ~ '"'}}>Home</a>
```

After format:
```
<a{{'href="'~path_for('home')~'"'}}>Home</a>
```

If I add a comment before or after the `li`, the formatter works properly:

Before format:
```
<li><a href="{{ path_for('home') }}">Home</a></li>
{# test #}
```

After format:
```
<li>
    <a href="{{ path_for('home') }}">Home</a>
</li>
{# test #}
```

**Comment by mblode** [comment]
This has been fixed in the latest update 👍

**Comment by X-Tender** [comment]
Either it was never fixed of it reappeared again. I got this markup:
```
<ul>
	<li><a href="{{ path }}">Hello</a></li>
</ul>
```
which gets formated to this:
```
<ul>
	<li><ahref="{{ path }}">Hello</a></li>
</ul>
```

Version 0.9.0

**Comment by mblode** [comment]
Fixed nested Twig expressions in href attributes in 0.12.0 and added regression coverage.
