### ISSUE TITLE
Format Document affecting Twig replace() within HTML tag

### ISSUE THREAD

**Issue by AnthonyANI** [mblode/vscode-twig-language-2#47]
I've identified potentially unwanted behavior when using Format Document that affects the values within a Twig replace() that resides within an HTML tag.

The following code is designed to remove "tabs" (four spaces) from the included twig file:
![image](https://user-images.githubusercontent.com/1095768/58972580-7a125c80-8783-11e9-92c9-6112108b5ab8.png)

It becomes the following after Format Document:
![image](https://user-images.githubusercontent.com/1095768/58972643-a201c000-8783-11e9-8cd2-93767f83fcb3.png)

This of course causes the replace to remove every single space rather than four spaces together as originally intended, and breaks the HTML in the included Twig file.

For my current project, I realized I didn't need the replace at all so was able to avoid the issue and continue using Format Document.  I also just learned of a Twig filter that can do away with this type of replace altogether: https://twig.symfony.com/doc/2.x/filters/spaceless.html  Though I figured it couldn't hurt submitting this since it appears to be unintentional behavior and a fix for it may prevent future issues when replace() is used within HTML tags.

P.S. Funnily enough, the GitHub code formatter also changed four spaces to one space, so I had to use screenshots to illustrate the problem.

**Comment by mblode** [comment]
0.12.0 preserves string contents inside Twig expressions. Added regression tests for replace and escape parameters.
