### ISSUE TITLE
Use single quotes in Craft "switch" snippet 

### ISSUE THREAD

**Issue by frankharrison-wj** [mblode/vscode-twig-language-2#7]
This is a really minor one but: the "switch" snippet for Craft uses double quotes around the case statements (`{% case "value1" %}`). Would be nice to have those as single quotes (`{% case 'value1' %}`) to make it consistent with the other snippets. (I've not tried all the snippets – but that's the only single-quote one I've seen so far.) Great work on this extension though!

**Comment by frankharrison-wj** [comment]
Great, thank you!

**Comment by mblode** [comment]
Configurable snippet quotes are still not included. 0.12.0 preserves quotes in your existing code.
