### ISSUE TITLE
Snippet trans: missing endtrans

### ISSUE THREAD

**Issue by ArmandPhilippot** [mblode/vscode-twig-language-2#72]
The snippet `trans` is not working properly. On completion, after typing "_trans_", the end block is not correct.

**Currently:**
```
{% trans %}{% trans %}
```
**Instead of:**
```
{% trans %}{% endtrans %}
```
**Demo:**

![trans](https://user-images.githubusercontent.com/59021693/99420070-13441d00-28fd-11eb-854e-21bac77833b8.gif)

**Comment by EnzoKilm** [comment]
The problem still persists for me 
![image](https://user-images.githubusercontent.com/20820044/127032590-15edaf0f-7f48-407a-9845-4b74a8e857fe.png)

**Comment by ArmandPhilippot** [comment]
I think the extension has not been updated neither on [VS Code marketplace](https://marketplace.visualstudio.com/items?itemName=mblode.twig-language-2) nor on [Open VSX marketplace](https://open-vsx.org/extension/mblode/twig-language-2).
From "*Project details*" on VS Code marketplace, I see: `Last updated 24/08/2020 à 00:54:46`.
From Open VSX, I see: `Published 1 year ago` (which correspond to `19/06/2020 à 06:27` on mousehover)

While my fix #73 dates from 17/11/2020.
(I have not converted the dates, they are in French format)

**Comment by EnzoKilm** [comment]
Thanks for your quick reply, do you know if an update is planned in the near future then ?

**Comment by ArmandPhilippot** [comment]
No idea. It seems that the project is no longer active... And I think only @mblode can post a new update on the markeplaces.

While waiting for an update, a possible workaround is to modify `snippets.json` (line 669) locally. On Linux, the file is in `$HOME/.vscode-oss/extensions/mblode.twig-language-2-0.9.1/src/snippets/`.

**Comment by EnzoKilm** [comment]
Thanks !

**Comment by mblode** [comment]
The trans block snippet includes endtrans in 0.12.0. Thanks for flagging this.
