### ISSUE TITLE
snippet : prefix trans

### ISSUE THREAD

**Issue by Boulette67** [mblode/vscode-twig-language-2#75]
Error at line 669
![image](https://user-images.githubusercontent.com/3381016/106385245-88d56a80-63cf-11eb-8dd8-22ae01a5046e.png)

**Comment by Boulette67** [comment]
It's fixed in your project but not in extension package 0.9.2

**Comment by Boulette67** [comment]
ArmandPhilippot fixed it 3 months ago. Sorry :)

**Comment by Boulette67** [comment]
ArmandPhilippot fixed it 3 months ago. Sorry :)

**Comment by mblode** [comment]
The trans block snippet includes endtrans in 0.12.0. Thanks for flagging this.
