### ISSUE TITLE
Format not respecting my indentation settings

### ISSUE THREAD

**Issue by achord** [mblode/vscode-twig-language-2#8]
I have my settings to indent 2 spaces instead of 4. When I format using twig-language-2, it indents all code with 4 spaces. Is this a bug or a something I can configure?

**Comment by achord** [comment]
Note I ave this in my setting:

```
"editor.insertSpaces": true,
"editor.tabSize": 2,
```

**Comment by mblode** [comment]
That's interesting. I began to test it and I ran into the same problems as you. There is a chance that Twig Language 2 is just not respecting the editor settings but I will try to fix it ASAP. Thanks for submitting the issue 👍

**Comment by mblode** [comment]
Just add this to your editor config:

```
"twig-language-2.tabSize": 2,
```

**Comment by dejavu1987** [comment]
Hi @mblode I am using v. 0.9.2
I have added `"twig-language-2.tabSize": 2,` as you mentioned above and still it is formatting with tabs instead of spaces.

**Comment by jcorrego** [comment]
Same issue here

**Comment by josephcrowell** [comment]
Same here

**Comment by inlikealion** [comment]
@JSchreff I found that on my own, too. However, this plugin _STILL_ doesn't respect my VS Code local settings, NOR the local `.editorconfig` settings. I have to manually change these settings in Twig Language 2 extension to match.

This is a non-starter for me - how are we supposed to enforce code standards on our team if it requires everyone to manually adjust this extension's settings and cross their fingers that they did it right? It's wild to me that the plugin is so opinionated and doesn't even follow its own UI promise ("Tab Size: 0 will default to the editor's tab size.").

**Comment by unipro-LeighMason** [comment]
I cant see any way to stop this extension using tabs. It doesn't seem to listen to the   "twig-language-2.indentStyle": "space", setting

**Comment by overclick-x86** [comment]
I managed to solve it by removing the extension Beautify by HookyQR v1.5.0. It was conflicting with Twig Language 2.

**Comment by alisonjo315** [comment]
I struggled with this, too.  My findings, in case it helps anyone else:
* Twig Language 2 does not respect my .editorconfig file (it's in my project root, and it has `root = true` set in it). 
* BUT, it does seem to respect my `editor.tabSize` setting in VS Code.
  * To test:
    * I changed `editor.tabSize` to a weird value that absolutely couldn't come from any other settings or config files (`3`).
    * I set `twig-language-2.indentStyle` to `space`.
    * I changed `twig-language-2.tabSize` to its default (`0`).
    * Then, I restarted VS Code, and did "Format Document" on a twig file -- all my indentations became 3 spaces.

----

**Anyway, to get things the way I actually wanted them to be! --**
* I have `twig-language-2.formatting` enabled, so I can use the "Format Document" thing in the context menu.
* Twig-language-2 settings:
```json
    "twig-language-2.indentStyle": "space",
    "twig-language-2.tabSize": 2,
```
* I needed to make sure NOT to set "Indent Level" to 2 -- I think I did that when I was flailing around trying different settings, and, I don't really understand the purpose of it, but it seems to pile onto the regular tabSize setting?
  * in other words, the following setting was "bad" and I removed/reset it:
```json
  "twig-language-2.indentLevel": 2,
```
* [As unipro-LeighMason indicated](https://github.com/mblode/vscode-twig-language-2/issues/8#issuecomment-1190106129), any time I change _any_ of these settings, I have to restart VS Code (even though it doesn't prompt me to do so).

----

✏️✏️✏️
Maybe the help text under "Twig-language-2: Tab Size" could say:
> 0 will default to the editor's tab size (`editor.tabSize`). This formatter will not use the `indent_size` setting declared in `.editorconfig` files.

And maybe the help text under "Twig-language-2: Indent Style" could say:
> Choose to indent using tabs or spaces. This formatter will not use the "Editor: Insert Spaces" setting, nor will it use the `indent_style` setting declared in `.editorconfig` files.

----

Anyway, thanks for the extension, I'm very glad to have it!

**Comment by tc0o** [comment]
Recap.

Steps: (I’m stuck at step 2. Hopefully, this will help people who want to set the indent style to spaces.)
- Add those to settings.json
```jsonc
{
    "twig-language-2.indentStyle": "space",
    "twig-language-2.tabSize": 2, // or "editor.tabSize": 2,
}
```
- "Developer: Reload Window"
- "Format Document"

**Comment by mblode** [comment]
0.12.0 uses the document’s tab size and indentation style. Added tests for spaces, tabs and settings changes.
