### ISSUE TITLE
Extension adds extra markup when document is formatted

### ISSUE THREAD

**Issue by charlesRepo** [mblode/vscode-twig-language-2#9]
`<input type="hidden" name="test" value="{{ id["index"] }}">`
I have the auto-formatting enabled on save. 
When saving the above code, i get this:
`<input type="hidden" name="test" value="{{ id["index"] }}"="index"] }}"">`

The bug disappear when I substitute the double quotes with single quotes inside the brackets:
`<input type="hidden" name="test" value="{{ id['index'] }}">`

**Comment by mbbillz** [comment]
@mblode Related to this is when you have a boolean attribute e.g `<button bool-example></button` this formats to `<button bool-example="bool-example"></button>` this adds a lot of unnecessary markup.

**Comment by mblode** [comment]
Fixed the nested-quote markup corruption in 0.12.0 and added regression coverage.
