### ISSUE TITLE
Weird emmet for a lot of twig codes

### ISSUE THREAD

**Issue by FrDH** [mblode/vscode-twig-language-2#91]
In the video, I type `i` and get a lot of options, including `if`. When I keep typing and have `if`, the only two options are `ifr` and `iframe`, both rendering the HTML for an iframe. When I keep typing and have `ifb`, no suggestion is made at all.
This weird behavior changed somewhere this morning. Is it supposed to work like this? 

https://user-images.githubusercontent.com/1387163/216939484-4cc43beb-ddb8-4880-b873-04f31dfcc5c5.mov

When trying to type a `for` loop its like this:
- `f` shows a lot of suggestions, including `for`
- `fo` shows `font`, `footer`, `form`, `form:get` and `form:post`
- `for` shows `form`, `form:get` and `form:post`

**Comment by koalawesley** [comment]
I have the same issue!

**Comment by zalodias** [comment]
Same issue here, I believe this might be related to a new VSCode update - as soon as I updated, I started to get this problem. Somehow it must have created a conflict with these snippets.

**Comment by mijewe** [comment]
Looks like this is fixed on VSCode 1.75.1

**Comment by mblode** [comment]
Emmet handling inside Twig expressions is still limited. I haven’t confirmed this case fixed in 0.12.0.
