### ISSUE TITLE
Indentation settings help text

### ISSUE THREAD

**Issue by alisonjo315** [mblode/vscode-twig-language-2#94]
See #8 for background.

Maybe the help text under "Twig-language-2: Tab Size" could say:
> 0 will default to the editor's tab size (`editor.tabSize`). This formatter will not use the `indent_size` setting declared in `.editorconfig` files.

And maybe the help text under "Twig-language-2: Indent Style" could say:
> Choose to indent using tabs or spaces. This formatter will not use the "Editor: Insert Spaces" setting, nor will it use the `indent_style` setting declared in `.editorconfig` files.

And, maybe somewhere [on the extension info page](https://marketplace.visualstudio.com/items?itemName=mblode.twig-language-2) (i.e. under Installation) -- or among the extension settings -- it could say:
> Restart VS Code after making changes to Twig-language-2 settings.

----

_Originally posted by @alisonjo315 in https://github.com/mblode/vscode-twig-language-2/issues/8#issuecomment-1444782600_

**Comment by mblode** [comment]
0.12.0 uses the document’s tab size and indentation style. Added tests for spaces, tabs and settings changes.
